### ISSUE TITLE
Problem getting correct DotNetCore version

### ISSUE THREAD

**Issue by CarlGraff** [LambdaSharp/Alexa-AdventureBot-Challenge#3]
I tried to get this challenge to work on my Mac but there seems to be issues with El Capitan and the dotnet tool chain per many hits on Google. So in order to get a stable environment to attend future meetups I installed Ubuntu 16.10 on a VM.
When I get to the part to" dotnet run ../assets/sample-adventure.json" I get this error message:
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.1
      1.1.2
  - Alternatively, install the framework version '1.0.5'.

Sooo.... I started by installing version 1.1.2 most current and then 1.1.1 but as shown above I need to either specifically download 1.0.5 (which is only available on Ubuntu 16.04 I think) or modify code base. I will try to download 1.0.5 on Ubuntu 16.10 and if that doesn't work I will have to start from scratch with a 16.04 Ubuntu. I believe that the code base could be changed to use a newer dotnet core but I would have to learn a lot of stuff I think before I attempt that.

Any suggested are welcome. Especially to help me understand how to prepare with correct setup for future Lambda Sharp meetups.

Thanks,
  Carl graffcarl@gmail.com

**Comment by bjorg** [comment]
Hi Carl,

I'm running OSX El Capitan as well. You should have no problems with.

Let's see if we can figure this out. First, you have to make sure you install .NET Core 1.0.x. In newer, installers, it's included with the 1.1.x releases. 1.0.x is the Long Term Stable release and is the only version supported by AWS until 2.0 gets an LTS release.

Second, check if you installed mono or a preview release of .NET Core in the past. These can mess up your environment path and cause confusion.

Hope, this helps. If not, I'm happy to assist with getting it figured out since it should just work on OSX.

**Comment by CarlGraff** [comment]
I ran a script that supposedly removed all previous .net core versions - I will run it again to be sure.
I will have to see if I ever installed mono and I will revolve it if I have.

It would help if you could send me any command line stuff that checks if I have the proper tools and versions - such as:
$ dot not
$ dot net —version
$ aws  cli --version
$ pip —version
$ python —version
...
This is a pretty involved dependency stack so knowing what the correct version for each piece might be important.

I think you are indicating that I need to install the stable release - not the newest release - so I will try that.

I have installed CentOS 7 in VM in Virtualbox and I will try yo get that working regardless if I get it to work on OS X El Capitan.

I think it would be a good idea to create an EC2 template specific to Lambda # so that everyone can just create an EC2 instance in their account based on this template - I will look into that as well.

Best,
  Carl
“Quick to smile, slow to frown, brighter day everyone"

**Comment by bjorg** [comment]
The EC2 instance is not a bad idea, but it would prevent running an IDE like VS Code to do the work.

If you've installed .NET Core in the past, it's likely you have some lingering garbage sitting around. I know I did and it gave me quite a bit of grief to get rid of it. However, since then, I've found the tooling to be quite solid.

To clarify, if you install .NET Core 1.1 on OSX, it will also install .NET Core 1.0 since its the LTS version.

Here's my tooling info. Hope it helps!
```
~> dotnet

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

To get started on developing applications for .NET Core, install the SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

```
~> dotnet --version
1.0.1
```

```
~> aws --version
aws-cli/1.11.84 Python/3.6.1 Darwin/15.6.0 botocore/1.5.47
```

```
~> pip --version
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)
```

```
~> python --version
Python 2.7.10
```

**Comment by CarlGraff** [comment]
Thanks Steve - yeh I though about not being able to use a graphical editor / IDE but perhaps just setting up the capability to transfer files between local machine and EC2 instance would help (FileZilla?)
I also will follow through with the CentOS KDE workstation VirtualBox VM and if I can get that to work I’ll see if a can create a sharable appliance that is ready to go in case others want to use it.

I will try what you indicate below on OSX and keep you posted,

Thanks for your quick response to this,
  Carl

**Comment by CarlGraff** [comment]
This is only difference so far:
	 aws --version
		aws-cli/1.11.111 Python/2.7.10 Darwin/15.6.0 botocore/1.5.74

So I will try to revert to older version of aws-cli and also do this suggestion:

	To get started on developing applications for .NET Core, install the SDK from:
 	 http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

Then if that doesn’t work I will try removing any and all dotnet and mono then reinstalling.
Also I copied the credentials from my default aws profile which I believe was for us-west-1 and setup this profile for the challenge:

.aws/config
	[profile lambdasharp]
	region = us-east-1

.aws/credentials
[lambdasharp]
	aws_access_key_id = AKxxxxxxxxxxH2AMA <-- from defualt 
	aws_secret_access_key = Rra6lSs+UCGDxxxxxxxxxxAgoDNjz <-- from default 

If I haven’t overwhelmed you too much at this point:
1. I did get the command line adventure game running,
2. The actual error I get is at tis point:
	1. Change folder to the lambda function: `cd AdventureBot.Alexa`
	2. Publish the lambda function: `dotnet lambda deploy-function`
	
==============================
AdventureBot.Alexa(master) > dotnet lambda deploy-function
Executing publish command
... invoking 'dotnet publish', working folder '/Users/carlgraff/Desktop/Training_Job_Prep/AWS/AWS-MagicNight/June2017-Alexa_AdventureBot/June2017-AdventureBot/AdventureBot.Alexa/bin/Release/netcoreapp1.0/publish'
AdventureBot.Alexa(master) > 
==================================

No error message but doesn’t seem to compete all the deploy steps.

**Comment by CarlGraff** [comment]
Tried everything I can on OSX and have all the same versions as you. Adrian Drummond offered to troubleshoot this with me when/if he has time. So it would be best I think to have another set of eyes look at this either in person somewhere like at MindTouch or via some video conference (google hangout or TeamViewer ..etc). I will pay for someone to help me with this.

Meanwhile I will try and get this to work on my CentOS VM and perhaps an EC2 instance.

Best,
  Carl

**Comment by CarlGraff** [comment]
Now trying on CentOS and get this message in Alexa console:
Error: Please make sure that "Alexa Skills Kit" is selected for the event source type of arn:aws:lambda:us-east-1:734071252383:function:LambdaSharp-AlexaEcho

	arn:aws:lambda:us-east-1:XXXXXXXXXX:function:LambdaSharp-AlexaEcho

using the 7…...….3 you provided

Is this service still arn service still up and running with the same ID?

**Comment by bjorg** [comment]
No, I stopped the lambda function. You can either publish the [Alexa Echo](https://github.com/LambdaSharp/AlexaEcho) function or just skip to step 2.

**Comment by CarlGraff** [comment]
OK thanks - I got step 2 to work on CentOS VM - so I will save a snapshot of VM now and go back to OSX and try one last thing.

Best,
  Carl

**Comment by bjorg** [comment]
Closing.

**Comment by CarlGraff** [comment]
Thanks for looking into this for me back when it happened Steve. I should have let you know that it was definitely something in my Mac environment because I spun up a virtual Ubuntu machine and started from scratch and everything worked. fine.

**Comment by bjorg** [comment]
No worries. I was just updating the challenge for .NET Core 2.1 and saw it had an open issue. I had totally forgotten about it! :)
